stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
    - data/raw_tweets.csv
    - src/data_ingestion.py
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw_tweets.csv
    - src/data_preprocessing.py
    outs:
    - data/processed_tweets.csv
  features:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed_tweets.csv
    - src/feature_engineering.py
    outs:
    - data/features.npz
    - data/labels.csv
    - models/vectorizer.pkl
  train:
    cmd: python src/model_building.py
    deps:
    - data/features.npz
    - data/labels.csv
    - src/model_building.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
  evaluate:
    cmd: python src/model_evaluation.py
    deps:
    - data/features.npz
    - models/model.pkl
    - src/model_evaluation.py
